version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "shop"
      POSTGRES_USER: "shop_user"
      POSTGRES_PASSWORD: "pgpwd4habr"
      volumes: pgdata:/var/lib/postgresql/data
    
    ports:
      - "5432:5432"